### ISSUE TITLE
[Question] not able to receive calls when App closed

### ISSUE THREAD

**Issue by fabriziomoscon** [twilio/twilio-client-quickstart-android#36]
I have implemented a quickstart app using the new Programmable Voice SDK, following this tutorial: https://www.twilio.com/docs/api/voice-sdk/android/getting-started
Everything works great, and **I am able to receive calls even though the app is closed/killed**

I was under the impression that I could receive calls even though the app is closed/killed also using the Client SDK. But when I tried to do that I discovered that actually it is not possible. I am using `com.twilio:client-android:1.2.18`

Could please somebody at Twilio clarify what is the expected behaviour? Maybe highlighting how the Client SDK compare with Programmable Voice SDK feature wise.

Cheers

**Comment by idelgado** [comment]
@fabriziomoscon One of the shortcomings of the `client-android` library is that it relied on an Android Service that we started upon initialization to receive incoming calls. This Service established a connection with the Twilio backend allowing incoming calls to be received through this channel. Unfortunately, this mechanism is not reliable, since the Android OS is free to kill the Service even when the app is in the background. Android makes no guarantees that a Service will be long-lived and in fact discourages this behavior. As a result, in some cases, developers would not receive incoming calls as they might expect because the Service had been killed by the Android OS.

In `voice-android`, this problem is solved by providing incoming call messages via GCM allowing the developer to manage incoming calls without the need of running an Android Service. If your use case requires receiving calls when the app is closed or in the background I would highly encourage you to switch to `voice-android` so you can use GCM instead. If you are building this application on iOS, the same functionality is available via APNS as well (https://www.twilio.com/docs/api/voice-sdk/ios/getting-started).

**Comment by fabriziomoscon** [comment]
Thanks. That makes totally sense!

**Comment by arvd** [comment]
I have fatching same issues and I have write code in app debate but still not receiving notification while application close and I got notification in background as well as in foreground. can you please tell help me.

**Comment by monikamitruka24** [comment]
Same question. It is working fine in foreground and background but don't know how to get it in killed state. If anyone can help me.
